name: Test run of tests scrapers

on:
  push:
    branches: [ master ]
    paths:
    - 'scrapers/**'
    - '!scrapers/scrape_??.py'
    - '!scrapers/*_districts.py'
    - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'scrapers/**'
    - '.github/workflows/**'
  workflow_dispatch: ~

jobs:
  validate:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Remove broken apt repos
      run: |
        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

    - name: Install dependencies
      run: |
        npm ci
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        sudo apt update || true # do not fail if update does not work
        sudo apt-get install poppler-utils
        sudo apt-get install chromium-browser

    - name: Test run of all tests scrapers
      run: ./scrapers/test_tests_scraper.sh

